# Generated by Django 6.0.1 on 2026-04-02 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0011_alter_aluno_endereco_alter_sexo_descricao'),
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='endereco',
            field=models.CharField(blank=True, default='Não informado', max_length=255),
        ),
        migrations.AddField(
            model_name='professor',
            name='sexo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='aluno.sexo'),
        ),
        migrations.AddField(
            model_name='professor',
            name='telefone',
            field=models.CharField(default='Não informado', max_length=20),
        ),
    ]
