# Generated by Django 6.0.1 on 2026-04-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_professor_endereco_professor_sexo_professor_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique='true'),
        ),
    ]
