# Generated by Django 6.0.1 on 2026-04-07 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0003_professor_email'),
        ('sexo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='sexo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sexo.sexo'),
        ),
    ]
