# Generated by Django 6.0.3 on 2026-03-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='email',
            field=models.EmailField(default='sememail@gmail.com', max_length=100),
        ),
        migrations.AddField(
            model_name='aluno',
            name='endereco',
            field=models.CharField(default='Não informado', max_length=255),
        ),
        migrations.AddField(
            model_name='aluno',
            name='sexo',
            field=models.CharField(default='Não informado', max_length=20),
        ),
        migrations.AddField(
            model_name='aluno',
            name='telefone',
            field=models.CharField(default='Não informado', max_length=20),
        ),
    ]
