# Generated by Django 6.0.1 on 2026-03-30 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0010_alter_aluno_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='endereco',
            field=models.CharField(blank=True, default='Não informado', max_length=255),
        ),
        migrations.AlterField(
            model_name='sexo',
            name='descricao',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
