# Generated by Django 6.0.1 on 2026-04-07 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0011_alter_aluno_endereco_alter_sexo_descricao'),
        ('curso', '0001_initial'),
        ('professor', '0004_alter_professor_sexo'),
        ('sexo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='sexo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sexo.sexo'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='curso.curso'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Sexo',
        ),
    ]
