# Generated by Django 6.0.1 on 2026-04-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0012_alter_aluno_sexo_aluno_curso_delete_sexo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ['-data_criacao']},
        ),
        migrations.AddField(
            model_name='aluno',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
