# Generated by Django 6.0.3 on 2026-03-17 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0003_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.EmailField(default='sememail@gmail.com', max_length=100, unique='true'),
        ),
    ]
