# Generated by Django 6.0.2 on 2026-02-25 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='professor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='professor.professor'),
            preserve_default=False,
        ),
    ]
