# Generated by Django 6.0.2 on 2026-02-24 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='bairro',
            field=models.CharField(default='Centro', max_length=100),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cep',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
