# Generated by Django 6.0.2 on 2026-02-24 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_aluno_bairro_aluno_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='cidade',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='aluno',
            name='estado',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='aluno',
            name='logradouro',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='bairro',
            field=models.CharField(default='', max_length=100),
        ),
    ]
