# Generated by Django 6.0.2 on 2026-02-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0003_aluno_cidade_aluno_estado_aluno_logradouro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='numero',
            field=models.CharField(default='', max_length=10),
        ),
    ]
