# Generated by Django 6.0.1 on 2026-04-07 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professor', '0003_professor_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank='false', max_length=50)),
                ('carga_horaria', models.IntegerField(blank='false', default=0)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='professor.professor')),
            ],
        ),
    ]
